name: Build shapeJumper

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses-dev libsfml-dev

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install sfml ncurses

    - name: Build
      run: make

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: shapeJumper-${{ runner.os }}
        path: shapeJumper
